# Generated by Django 4.1.7 on 2023-03-08 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=16, primary_key=True, serialize=False)),
            ],
        ),
    ]
