# Generated by Django 4.1.7 on 2023-03-08 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='owner',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
