# Generated by Django 4.1.7 on 2023-03-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_created_on_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='identity_key',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='name',
            field=models.CharField(default=' ', max_length=64),
            preserve_default=False,
        ),
    ]
