# Generated by Django 4.1.7 on 2023-03-16 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_organisation_identity_key_organisation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('identity_key', models.CharField(max_length=256)),
                ('app_token', models.CharField(max_length=256)),
                ('wrapped_key_share', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organisation')),
            ],
        ),
    ]
