# Generated by Django 4.1.7 on 2023-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_organisation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_seed',
            field=models.CharField(default='', max_length=208),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='app_token',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='app',
            name='wrapped_key_share',
            field=models.CharField(max_length=406),
        ),
    ]
