# Generated by Django 4.1.7 on 2023-03-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_app_app_seed_alter_app_app_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
