# Generated by Django 4.2 on 2023-04-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_app_id_alter_customuser_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
