# Generated by Django 4.2 on 2023-04-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_app_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='version',
            new_name='app_version',
        ),
    ]
