# Generated by Django 4.2 on 2023-04-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_version_app_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
