# Generated by Django 4.2 on 2023-04-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_app_deleted_at_app_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='plan',
            field=models.CharField(choices=[('FR', 'Free'), ('PR', 'Pro'), ('EN', 'Enterprise')], default='FR', max_length=2),
        ),
    ]
