# Generated by Django 4.2.3 on 2023-08-01 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_environment_secret_secrettag_secretevent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentsecret',
            old_name='environment_token',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='environmentkey',
            name='environment_token',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='collection',
        ),
        migrations.AddField(
            model_name='secrettag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='secrettag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secrettag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SecretFolder',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.environment')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.secretfolder')),
            ],
        ),
        migrations.AddField(
            model_name='secret',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secretfolder'),
        ),
    ]
