# Generated by Django 4.2.3 on 2023-08-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_environment_token_environmentsecret_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='user',
        ),
        migrations.RemoveField(
            model_name='secretevent',
            name='collection',
        ),
        migrations.AddField(
            model_name='secretevent',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secretfolder'),
        ),
    ]
