# Generated by Django 4.2.3 on 2023-08-04 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

def migrate_org_owners(apps, schema_editor):
    OrgModel = apps.get_model('api', 'Organisation')
    OrgMemberModel = apps.get_model('api', 'OrganisationMember')

    for org in OrgModel.objects.all():
        OrgMemberModel.objects.create(user=org.owner, organisation=org, role='owner', identity_key=org.identity_key, created_at=org.created_at)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_secret_user_remove_secretevent_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationMember',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('dev', 'Developer')], default='dev', max_length=5)),
                ('identity_key', models.CharField(blank=True, max_length=256, null=True)),
                ('wrapped_keyring', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='environmentkey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organisationmember'),
        ),
        migrations.AlterField(
            model_name='environmentsecret',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organisationmember'),
        ),
        migrations.AlterField(
            model_name='secretevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organisationmember'),
        ),
        migrations.RunPython(migrate_org_owners),
        migrations.RemoveField(
            model_name='organisation',
            name='owner',
        ),
    ]
