# Generated by Django 4.2.3 on 2023-08-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_organisation_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretevent',
            name='timestamp',
        ),
    ]
