# Generated by Django 4.2.3 on 2023-08-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_secretevent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='identity_key',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
