# Generated by Django 4.2.3 on 2023-08-12 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_environment_wrapped_salt_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnvironmentSecret',
            new_name='EnvironmentToken',
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('identity_key', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=64)),
                ('wrapped_key_share', models.CharField(max_length=406)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organisationmember')),
            ],
        ),
    ]
