# Generated by Django 4.2.3 on 2023-08-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_environmentsecret_environmenttoken_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretfolder',
            name='color',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='secret',
            name='tags',
        ),
        migrations.AddField(
            model_name='secret',
            name='tags',
            field=models.ManyToManyField(to='api.secrettag'),
        ),
    ]
