# Generated by Django 4.2.3 on 2023-08-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_secretfolder_color_remove_secret_tags_secret_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretfolder',
            name='color',
        ),
        migrations.AddField(
            model_name='secrettag',
            name='color',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
