# Generated by Django 4.2.3 on 2023-08-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_secretfolder_color_secrettag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretevent',
            name='tags',
        ),
        migrations.AddField(
            model_name='secretevent',
            name='tags',
            field=models.ManyToManyField(to='api.secrettag'),
        ),
    ]
