# Generated by Django 4.2.3 on 2023-09-06 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_secretevent_tags_secretevent_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceToken',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=64)),
                ('wrapped_key_share', models.CharField(max_length=406)),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.app')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organisationmember')),
                ('keys', models.ManyToManyField(to='api.environmentkey')),
            ],
        ),
    ]
