# Generated by Django 4.2.3 on 2023-09-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_servicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
