# Generated by Django 4.2.3 on 2023-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_organisationmemberinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmemberinvite',
            name='apps',
            field=models.ManyToManyField(to='api.app'),
        ),
    ]
