# Generated by Django 4.2.3 on 2023-09-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_organisationmemberinvite_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmemberinvite',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('dev', 'Developer')], default='dev', max_length=5),
        ),
    ]
