# Generated by Django 4.2.3 on 2023-09-15 13:19

from django.db import migrations, models


def set_org_member_apps(apps, schema_editor):
    OrgMemberModel = apps.get_model('api', 'OrganisationMember')
    AppModel = apps.get_model('api', 'App')

    for org_member in OrgMemberModel.objects.all():
        org_apps = AppModel.objects.filter(
            organisation=org_member.organisation, is_deleted=False)
        org_member.apps.set(org_apps)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_organisationmemberinvite_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmember',
            name='apps',
            field=models.ManyToManyField(to='api.app'),
        ),
        migrations.RunPython(set_org_member_apps)
    ]
