# Generated by Django 4.2.3 on 2023-09-16 08:50

from django.db import migrations, models


def reset_deleted_field(apps, schema_editor):
    OrgMemberModel = apps.get_model('api', 'OrganisationMember')

    for org_member in OrgMemberModel.objects.all():
        org_member.deleted_at = None
        org_member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_organisationmember_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationmember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(reset_deleted_field)
    ]
