# Generated by Django 4.2.3 on 2023-09-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_organisationmember_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationmember',
            name='apps',
            field=models.ManyToManyField(related_name='members', to='api.app'),
        ),
    ]
