# Generated by Django 4.2.3 on 2023-09-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_organisationmember_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmember',
            name='wrapped_recovery',
            field=models.TextField(blank=True),
        ),
    ]
