# Generated by Django 4.2.3 on 2023-10-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_organisationmember_wrapped_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
