# Generated by Django 4.2.3 on 2023-11-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_personalsecret_isactive_alter_personalsecret_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalsecret',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
