# Generated by Django 4.2.7 on 2023-11-22 08:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_isactive_personalsecret_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerEnvironmentKey',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(max_length=256)),
                ('wrapped_seed', models.CharField(max_length=256)),
                ('wrapped_salt', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.environment')),
            ],
        ),
    ]
