# Generated by Django 4.2.7 on 2023-11-28 07:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_serverenvironmentkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentSync',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('cloudflare', 'Cloudflare')], max_length=50)),
                ('options', models.JSONField()),
                ('authentication', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.environment')),
            ],
        ),
    ]
