# Generated by Django 4.2.7 on 2023-11-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_environmentsync'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentsync',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
