# Generated by Django 4.2.7 on 2023-11-30 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_environmentsync_last_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentsync',
            name='service',
            field=models.CharField(choices=[('cloudflare_pages', 'Cloudflare Pages'), ('cloudflare_secrets', 'Cloudflare Secrets'), ('cloudflare_workers', 'Cloudflare Workers')], max_length=50),
        ),
        migrations.CreateModel(
            name='EnvironmentSyncEvent',
            fields=[
                ('meta', models.JSONField()),
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('env_sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.environmentsync')),
            ],
        ),
    ]
