# Generated by Django 4.2.7 on 2023-12-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_environmentsyncevent_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentsync',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=16),
        ),
    ]
