# Generated by Django 4.2.7 on 2023-12-20 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0048_delete_existing_syncs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentsync",
            name="service",
            field=models.CharField(
                choices=[
                    ("cloudflare_pages", "Cloudflare Pages"),
                    ("cloudflare_workers", "Cloudflare Workers"),
                    ("aws_secrets_manager", "AWS Secrets Manager"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="environmentsync",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("timed_out", "Timed out"),
                    ("failed", "Failed"),
                ],
                default="in_progress",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="environmentsyncevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("timed_out", "Timed out"),
                    ("failed", "Failed"),
                ],
                default="in_progress",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ProviderCredentials",
            fields=[
                (
                    "id",
                    models.TextField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "provider",
                    models.CharField(
                        choices=[("cloudflare", "Cloudflare"), ("aws", "AWS")],
                        max_length=50,
                    ),
                ),
                ("credentials", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="api.organisation",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="environmentsync",
            name="authentication",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.providercredentials",
            ),
        ),
    ]
