# Generated by Django 4.2.7 on 2023-12-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_environmentsync_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentsync',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'cancelled'), ('timed_out', 'Timed out'), ('failed', 'Failed')], default='in_progress', max_length=16),
        ),
        migrations.AlterField(
            model_name='environmentsyncevent',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'cancelled'), ('timed_out', 'Timed out'), ('failed', 'Failed')], default='in_progress', max_length=16),
        ),
    ]
