# Generated by Django 4.2.7 on 2024-02-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_environmentsync_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretfolder',
            name='parent',
        ),
        migrations.AddField(
            model_name='secret',
            name='path',
            field=models.TextField(default='/'),
        ),
        migrations.AddField(
            model_name='secretfolder',
            name='path',
            field=models.TextField(default='/'),
        ),
        migrations.AlterField(
            model_name='environmentsync',
            name='service',
            field=models.CharField(choices=[('cloudflare_pages', 'Cloudflare Pages'), ('aws_secrets_manager', 'AWS Secrets Manager'), ('github_actions', 'GitHub Actions'), ('hashicorp_vault', 'Hashicorp Vault')], max_length=50),
        ),
    ]
