# Generated by Django 4.2.7 on 2024-02-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_secretevent_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretfolder',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secretfolder'),
        ),
    ]
