# Generated by Django 4.2.7 on 2024-02-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_secretfolder_folder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secretfolder',
            unique_together={('environment', 'folder', 'name', 'path')},
        ),
    ]
