# Generated by Django 4.2.7 on 2024-02-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_secretfolder_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentsync',
            name='path',
            field=models.TextField(default='/'),
        ),
    ]
