# Generated by Django 4.2.7 on 2024-03-06 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_secretevent_service_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lockbox',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('allowed_views', models.IntegerField(null=True)),
            ],
        ),
    ]
