# Generated by Django 4.2.7 on 2024-06-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_environmentsync_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatedPhaseLicense',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('FR', 'Free'), ('PR', 'Pro'), ('EN', 'Enterprise')], default='EN', max_length=2)),
                ('seats', models.IntegerField()),
                ('tokens', models.IntegerField()),
                ('metadata', models.JSONField()),
                ('environment', models.CharField(max_length=255)),
                ('license_type', models.CharField(max_length=255)),
                ('signature_date', models.DateField()),
                ('issuing_authority', models.CharField(max_length=255)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organisation')),
            ],
        ),
    ]
