# Generated by Django 4.2.7 on 2024-07-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_activatedphaselicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercredentials',
            name='provider',
            field=models.CharField(choices=[('cloudflare', 'Cloudflare'), ('aws', 'AWS'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('hashicorp_vault', 'Hashicorp Vault'), ('hashicorp_nomad', 'Hashicorp Nomad'), ('railway', 'Railway')], max_length=50),
        ),
    ]
