# Generated by Django 4.2.7 on 2024-07-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_environmentsync_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='env_type',
            field=models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('prod', 'Production'), ('custom', 'Custom')], default='dev', max_length=7),
        ),
    ]
