# Generated by Django 4.2.7 on 2024-07-23 12:17

from django.db import migrations, models


def set_index_values(apps, schema_editor):
    Environment = apps.get_model("api", "Environment")
    for env in Environment.objects.all():
        if env.env_type == "dev":
            env.index = 0
        elif env.env_type == "staging":
            env.index = 1
        elif env.env_type == "prod":
            env.index = 2
        env.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_alter_environment_env_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="index",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_index_values),
    ]
