# Generated by Django 4.2.7 on 2024-07-25 16:10
from django.db import migrations


def correct_set_index_values(apps, schema_editor):
    Environment = apps.get_model("api", "Environment")
    for env in Environment.objects.all():
        if env.env_type.lower() == "dev":
            env.index = 0
        elif env.env_type.lower() == "staging":
            env.index = 1
        elif env.env_type.lower() == "prod":
            env.index = 2
        env.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_environment_index"),
    ]

    operations = [
        migrations.RunPython(correct_set_index_values),
    ]
