# Generated by Django 4.2.7 on 2024-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_correct_set_index_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activatedphaselicense',
            name='seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activatedphaselicense',
            name='tokens',
            field=models.IntegerField(null=True),
        ),
    ]
