# Generated by Django 4.2.15 on 2024-09-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20240910_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationmember',
            name='role',
        ),
    ]
