# Generated by Django 4.2.15 on 2024-09-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_rename_organisation_role_organisationmember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationmemberinvite',
            name='role',
        ),
    ]
