# Generated by Django 4.2.15 on 2024-09-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_alter_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
