# Generated by Django 4.2.15 on 2024-10-08 07:08

from django.db import migrations, models
from django.conf import settings


def set_sse_enabled(apps, schema_editor):
    App = apps.get_model("api", "App")
    Environment = apps.get_model("api", "Environment")
    ServerEnvironmentKey = apps.get_model("api", "ServerEnvironmentKey")

    apps = App.objects.all()
    for app in apps:
        app_envs = Environment.objects.filter(app=app).values_list("id")
        sse_enabled = ServerEnvironmentKey.objects.filter(
            environment_id__in=app_envs
        ).exists()
        app.sse_enabled = sse_enabled
        app.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0083_app_sse_enabled"),
    ]

    operations = [
        migrations.RunPython(set_sse_enabled),
    ]
