# Generated by Django 4.2.15 on 2024-10-22 07:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_serviceaccount_environmentkey_paths_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetoken',
            name='service_account',
        ),
        migrations.CreateModel(
            name='ServiceAccountToken',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('identity_key', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=64)),
                ('wrapped_key_share', models.CharField(max_length=406)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organisationmember')),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.serviceaccount')),
            ],
        ),
    ]
