# Generated by Django 4.2.15 on 2024-10-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_remove_servicetoken_service_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccount',
            name='apps',
            field=models.ManyToManyField(related_name='service_accounts', to='api.app'),
        ),
    ]
