# Generated by Django 4.2.15 on 2024-10-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_alter_serviceaccount_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretevent',
            name='service_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.serviceaccount'),
        ),
    ]
