# Generated by Django 4.2.15 on 2024-10-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_secretevent_service_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccounthandler',
            name='service_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlers', to='api.serviceaccount'),
        ),
    ]
