# Generated by Django 4.2.15 on 2024-10-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_alter_serviceaccounthandler_service_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccount',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to='api.organisation'),
        ),
    ]
