# Generated by Django 4.2.15 on 2024-11-04 08:36

from django.db import migrations
from api.utils.access.roles import default_roles


def add_default_roles(apps, schema_editor):
    Organisation = apps.get_model("api", "Organisation")
    Role = apps.get_model("api", "Role")
    OrganisationMember = apps.get_model("api", "OrganisationMember")

    # Create default roles for each organisation
    for organisation in Organisation.objects.all():
        for role_name, _ in default_roles.items():
            Role.objects.get_or_create(
                name=role_name,
                organisation=organisation,
                is_default=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0090_alter_serviceaccount_organisation"),
    ]

    operations = [
        migrations.RunPython(add_default_roles),
    ]
