# Generated by Django 4.2.15 on 2024-11-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_alter_environmentsync_service'),
        ('api', '0092_secretevent_service_account_token'),
    ]

    operations = [
    ]
