# Generated by Django 4.2.15 on 2025-01-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_merge_20241116_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='api.organisation'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='api.app'),
        ),
    ]
