# Generated by Django 4.2.16 on 2025-03-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_alter_environmentsync_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmemberinvite',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.role'),
        ),
    ]
