# Generated by Django 4.2.16 on 2025-04-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0096_organisationmemberinvite_role"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="secretfolder",
            unique_together=set(),
        ),
    ]
