# Generated by Django 4.2.16 on 2025-04-02 09:45

from django.db import migrations
from django.db.models import Count


def deduplicate_folders(apps, schema_editor):
    SecretFolder = apps.get_model("api", "SecretFolder")
    Secret = apps.get_model("api", "Secret")

    # Step 1: Find duplicate root folders (folder IS NULL) grouped by (environment_id, name, path)
    # Step 1: Find duplicate folders at all levels (root and subfolders)
    duplicates = (
        SecretFolder.objects.values(
            "environment_id", "folder_id", "name", "path"
        )  # Include subfolder grouping
        .annotate(count=Count("id"))
        .filter(count__gt=1)  # More than one exists
    )

    for duplicate in duplicates:
        env_id = duplicate["environment_id"]
        folder_id = duplicate["folder_id"]  # This could be NULL for root folders
        name = duplicate["name"]
        path = duplicate["path"]

        # Step 2: Get all duplicate folder instances (sorted deterministically)
        folders = list(
            SecretFolder.objects.filter(
                environment_id=env_id, folder_id=folder_id, name=name, path=path
            ).order_by(
                "id"
            )  # Ensure consistent selection
        )

        # Step 3: Pick one canonical folder
        canonical_folder = folders[0]
        duplicate_ids = [f.id for f in folders[1:]]  # All other duplicates

        # Step 4: Update `Secret` objects pointing to duplicate folders
        Secret.objects.filter(folder_id__in=duplicate_ids).update(
            folder=canonical_folder
        )

        # Step 5: Update **subfolders** that reference duplicate folders
        SecretFolder.objects.filter(folder_id__in=duplicate_ids).update(
            folder=canonical_folder
        )

        # Step 6: Delete all but the canonical folder
        SecretFolder.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        # ("api", "0098_remove_secretfolder_unique_secret_folder_and_more"),
        ("api", "0097_alter_secretfolder_unique_together_and_more")
    ]

    operations = [
        migrations.RunPython(deduplicate_folders),
    ]
