# Generated by Django 4.2.16 on 2025-04-23 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_remove_secretfolder_unique_secret_folder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAccessPolicy',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('allowed_ips', models.TextField(help_text='Comma-separated list of IP addresses or CIDR ranges (e.g. 192.168.1.1, 10.0.0.0/24)')),
                ('is_global', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='organisationmember',
            name='network_policies',
            field=models.ManyToManyField(blank=True, related_name='members', to='api.networkaccesspolicy'),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='network_policies',
            field=models.ManyToManyField(blank=True, related_name='service_accounts', to='api.networkaccesspolicy'),
        ),
    ]
