# Generated by Django 4.2.16 on 2025-04-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_networkaccesspolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkaccesspolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
