# Generated by Django 4.2.16 on 2025-04-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_networkaccesspolicy_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkaccesspolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_policies_created', to='api.organisationmember'),
        ),
        migrations.AddField(
            model_name='networkaccesspolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_policies_updated', to='api.organisationmember'),
        ),
    ]
