# Generated by Django 4.2.16 on 2025-07-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0104_deduplicate_environment_keys"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="environmentkey",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("user__isnull", False)
                ),
                fields=("environment", "user"),
                name="unique_envkey_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="environmentkey",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("service_account__isnull", False)
                ),
                fields=("environment", "service_account"),
                name="unique_envkey_service_account",
            ),
        ),
    ]
