# Generated by Django 4.2.22 on 2025-08-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_environmentkey_unique_envkey_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccounttoken',
            name='created_by_service_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tokens', to='api.serviceaccount'),
        ),
    ]
