# Generated by Django 4.2.22 on 2025-08-02 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_environmentkey_unique_envkey_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteEnvironment',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.environment')),
                ('organisation_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_environments', to='api.organisationmember')),
            ],
            options={
                'verbose_name': 'User Favorite Environment',
                'verbose_name_plural': 'User Favorite Environments',
                'unique_together': {('organisation_member', 'environment')},
            },
        ),
    ]
