# Generated by Django 4.2.22 on 2025-08-25 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_serviceaccounttoken_created_by_service_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('token_name_pattern', models.CharField(blank=True, max_length=128, null=True)),
                ('default_ttl_seconds', models.IntegerField(default=3600)),
                ('max_ttl_seconds', models.IntegerField(default=86400)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='identities',
            field=models.ManyToManyField(blank=True, related_name='service_accounts', to='api.identity'),
        ),
    ]
