# Generated by Django 4.2.22 on 2025-08-26 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_dynamicsecret_dynamicsecretlease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsecret',
            name='key_map',
            field=models.JSONField(default=list, help_text="Provider-agnostic mapping of keys: [{'id': '<key_id>', 'name': '<key_name>'}, ...]"),
        ),
        migrations.AddField(
            model_name='dynamicsecretlease',
            name='credentials',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dynamicsecretleaseevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamicsecretleaseevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('renewed', 'Renewed'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='created', max_length=50),
        ),
        migrations.AddField(
            model_name='dynamicsecretleaseevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicsecretleaseevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dynamicsecretleaseevent',
            name='organisation_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_events', to='api.organisationmember'),
        ),
        migrations.AddField(
            model_name='dynamicsecretleaseevent',
            name='service_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_events', to='api.serviceaccount'),
        ),
        migrations.AddField(
            model_name='dynamicsecretleaseevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicsecretlease',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('renewed', 'Renewed'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', help_text='Current status of the lease', max_length=50),
        ),
        migrations.AlterField(
            model_name='dynamicsecretleaseevent',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dynamicsecretleaseevent',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.dynamicsecretlease'),
        ),
    ]
