# Generated by Django 4.2.22 on 2025-08-28 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_dynamicsecret_key_map_dynamicsecretlease_credentials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsecretlease',
            name='cleanup_job_id',
            field=models.TextField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='dynamicsecretlease',
            name='credentials',
            field=models.JSONField(default=dict),
        ),
    ]
