# Generated by Django 4.2.22 on 2025-09-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_dynamicsecretlease_cleanup_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicsecret',
            name='key_map',
            field=models.JSONField(default=list, help_text="Provider-agnostic mapping of keys: [{'id': '<key_id>', 'key_name': '<encrypted_key_name>', 'key_digest': '<key_digest>'}, ...]"),
        ),
    ]
