# Generated by Django 4.2.22 on 2025-10-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_identity_serviceaccount_identities'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='secretevent',
            index=models.Index(fields=['secret_id', 'event_type', 'timestamp'], name='secret_event_history_idx'),
        ),
        migrations.AddIndex(
            model_name='secretevent',
            index=models.Index(fields=['-timestamp', 'environment'], name='secret_logs_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='secretevent',
            index=models.Index(fields=['environment', '-timestamp'], name='secret_logs_env_idx'),
        ),
    ]
