# Generated by Django 4.2.22 on 2025-10-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0111_identity_serviceaccount_identities"),
    ]

    operations = [
        migrations.AddIndexConcurrently(
            model_name="secretevent",
            index=models.Index(
                fields=["secret_id", "event_type", "timestamp"],
                name="secret_event_history_idx",
            ),
        ),
        migrations.AddIndexConcurrently(
            model_name="secretevent",
            index=models.Index(
                fields=["environment", "-timestamp"], name="secret_logs_env_idx"
            ),
        ),
        migrations.AddIndexConcurrently(
            model_name="secretevent",
            index=models.Index(
                fields=["service_account_token", "-timestamp"],
                name="sa_token_last_used_idx",
            ),
        ),
    ]
