# Generated by Django 4.2.27 on 2026-01-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_secretevent_secret_event_history_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pricing_version',
            field=models.IntegerField(default=1),
        ),
    ]
