# Generated by Django 4.2.27 on 2026-02-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_migrate_free_tier_to_v2_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
