# Generated by Django 4.2.28 on 2026-03-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_alter_environmentsync_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='type',
            field=models.CharField(choices=[('secret', 'Secret'), ('sealed', 'Sealed'), ('config', 'Config')], default='secret', max_length=10),
        ),
    ]
