# Generated by Django 4.2.28 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_secret_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretevent',
            name='type',
            field=models.CharField(choices=[('secret', 'Secret'), ('sealed', 'Sealed'), ('config', 'Config')], default='secret', max_length=10),
        ),
    ]
