# Generated by Django 4.2.29 on 2026-03-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auditevent_invite_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationmemberinvite',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organisationmember'),
        ),
        migrations.AddField(
            model_name='organisationmemberinvite',
            name='invited_by_service_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.serviceaccount'),
        ),
    ]
