# Generated by Django 4.2.29 on 2026-04-14 08:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_add_emailverification_and_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='require_sso',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrganisationSSOProvider',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('entra_id', 'Microsoft Entra ID'), ('okta', 'Okta')], max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('config', models.JSONField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sso_providers_created', to='api.organisationmember')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_providers', to='api.organisation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sso_providers_updated', to='api.organisationmember')),
            ],
            options={
                'unique_together': {('organisation', 'provider_type')},
            },
        ),
    ]
