# Generated by Django 4.2.29 on 2026-03-30 11:38

from django.db import migrations


def backfill_grants(apps, schema_editor):
    """
    Create an 'individual' EnvironmentKeyGrant for every existing EnvironmentKey.
    This ensures the grant-tracking system works from day one — all pre-existing
    keys are attributed to individual access.
    """
    EnvironmentKey = apps.get_model("api", "EnvironmentKey")
    EnvironmentKeyGrant = apps.get_model("api", "EnvironmentKeyGrant")

    grants_to_create = []
    for ek in EnvironmentKey.objects.filter(deleted_at__isnull=True).iterator():
        grants_to_create.append(
            EnvironmentKeyGrant(
                environment_key=ek,
                grant_type="individual",
                team=None,
            )
        )
        if len(grants_to_create) >= 1000:
            EnvironmentKeyGrant.objects.bulk_create(grants_to_create, ignore_conflicts=True)
            grants_to_create = []

    if grants_to_create:
        EnvironmentKeyGrant.objects.bulk_create(grants_to_create, ignore_conflicts=True)


def reverse_backfill(apps, schema_editor):
    """Remove all individual grants created by the forward migration."""
    EnvironmentKeyGrant = apps.get_model("api", "EnvironmentKeyGrant")
    EnvironmentKeyGrant.objects.filter(grant_type="individual", team__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0120_add_team_models"),
    ]

    operations = [
        migrations.RunPython(backfill_grants, reverse_backfill),
    ]
