# Generated by Django 4.2.29 on 2026-04-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_organisation_require_sso_organisationssoprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationssoprovider',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso_providers_created', to='api.organisationmember'),
        ),
        migrations.AlterField(
            model_name='organisationssoprovider',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso_providers_updated', to='api.organisationmember'),
        ),
    ]
