# Generated by Django 4.2.29 on 2026-04-14 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_backfill_environment_key_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='scim_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_service_accounts', to='api.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_teams', to='api.organisationmember'),
        ),
        migrations.CreateModel(
            name='SCIMUser',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('scim_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organisationmember')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_users', to='api.organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SCIMToken',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('token_prefix', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organisationmember')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_tokens', to='api.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='SCIMGroup',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('scim_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_groups', to='api.organisation')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scim_group', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='SCIMEvent',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('user_reactivated', 'User Reactivated'), ('group_created', 'Group Created'), ('group_updated', 'Group Updated'), ('group_deleted', 'Group Deleted'), ('member_added', 'Member Added to Group'), ('member_removed', 'Member Removed from Group')], max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=8)),
                ('resource_type', models.CharField(choices=[('user', 'User'), ('group', 'Group')], max_length=16)),
                ('resource_id', models.TextField(blank=True)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(default=dict)),
                ('request_method', models.CharField(blank=True, max_length=8)),
                ('request_path', models.TextField(blank=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_events', to='api.organisation')),
                ('scim_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.scimtoken')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='scimuser',
            constraint=models.UniqueConstraint(fields=('external_id', 'organisation'), name='unique_scim_user_external_id'),
        ),
        migrations.AddConstraint(
            model_name='scimuser',
            constraint=models.UniqueConstraint(fields=('email', 'organisation'), name='unique_scim_user_email'),
        ),
        migrations.AddConstraint(
            model_name='scimgroup',
            constraint=models.UniqueConstraint(fields=('external_id', 'organisation'), name='unique_scim_group_external_id'),
        ),
        migrations.AddIndex(
            model_name='scimevent',
            index=models.Index(fields=['organisation', '-timestamp'], name='scim_event_org_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='scimevent',
            index=models.Index(fields=['scim_token', '-timestamp'], name='scim_event_token_ts_idx'),
        ),
    ]
