# Generated by Django 4.2.29 on 2026-05-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_invite_sa_inviter'),
        ('api', '0122_sso_audit_fks_set_null'),
    ]

    operations = [
    ]
