# Generated by Django 4.2.29 on 2026-04-01 17:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_add_scim_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='scim_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scimtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SCIMEvent',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('user_reactivated', 'User Reactivated'), ('group_created', 'Group Created'), ('group_updated', 'Group Updated'), ('group_deleted', 'Group Deleted'), ('member_added', 'Member Added to Group'), ('member_removed', 'Member Removed from Group')], max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=8)),
                ('resource_type', models.CharField(choices=[('user', 'User'), ('group', 'Group')], max_length=16)),
                ('resource_id', models.TextField(blank=True)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(default=dict)),
                ('request_method', models.CharField(blank=True, max_length=8)),
                ('request_path', models.TextField(blank=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_events', to='api.organisation')),
                ('scim_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.scimtoken')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organisation', '-timestamp'], name='scim_event_org_ts_idx'), models.Index(fields=['scim_token', '-timestamp'], name='scim_event_token_ts_idx')],
            },
        ),
    ]
