# Generated by Django 4.2.30 on 2026-05-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_merge_20260509_1024'),
        ('api', '0126_populate_team_owner'),
    ]

    operations = [
    ]
