# Generated by Django 4.2.30 on 2026-06-15 10:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_wipe_orphan_envkeys_from_deleted_sas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotatingSecret',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('path', models.TextField(default='/')),
                ('provider', models.CharField(help_text='Rotation provider id (resolved against the rotation provider registry).', max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('key_map', models.JSONField(default=list, help_text="Provider-agnostic mapping of keys: [{'id': '<key_id>', 'key_name': '<encrypted_key_name>', 'key_digest': '<key_digest>'}, ...]")),
                ('rotation_interval', models.DurationField(help_text='How often a new credential is minted.')),
                ('revocation_delay', models.DurationField(default=datetime.timedelta, help_text='How long Phase waits before revoking the previous credential after a rotation. 0 = revoke immediately on rotation.')),
                ('next_rotation_at', models.DateTimeField(blank=True, null=True)),
                ('rotation_job_id', models.TextField(default=uuid.uuid4)),
                ('paused_remaining', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='healthy', max_length=20)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_reason', models.TextField(blank=True)),
                ('consecutive_failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RotatingSecretCredential',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expiring', 'Expiring'), ('revoking', 'Revoking'), ('revoked', 'Revoked'), ('mint_failed', 'Mint Failed'), ('revoke_failed', 'Revoke Failed')], default='pending', max_length=20)),
                ('provider_credential_id', models.TextField(blank=True)),
                ('encrypted_values', models.JSONField(default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_failure_reason', models.TextField(blank=True)),
                ('revoke_job_id', models.TextField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rotating_secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='api.rotatingsecret')),
            ],
        ),
        migrations.AddField(
            model_name='secret',
            name='rotating_output_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='resource_type',
            field=models.CharField(choices=[('app', 'App'), ('env', 'Environment'), ('role', 'Role'), ('sa', 'ServiceAccount'), ('member', 'OrganisationMember'), ('policy', 'NetworkAccessPolicy'), ('pat', 'UserToken'), ('sa_token', 'ServiceAccountToken'), ('svc_token', 'ServiceToken'), ('invite', 'Invite'), ('team', 'Team'), ('rs', 'RotatingSecret')], max_length=10),
        ),
        migrations.AlterField(
            model_name='providercredentials',
            name='provider',
            field=models.CharField(choices=[('cloudflare', 'Cloudflare'), ('aws', 'AWS'), ('aws_assume_role', 'AWS Assume Role'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('hashicorp_vault', 'Hashicorp Vault'), ('hashicorp_nomad', 'Hashicorp Nomad'), ('railway', 'Railway'), ('vercel', 'Vercel'), ('render', 'Render'), ('azure', 'Azure'), ('openai', 'OpenAI'), ('litellm', 'LiteLLM')], max_length=50),
        ),
        migrations.CreateModel(
            name='RotatingSecretEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('config_created', 'Config Created'), ('config_updated', 'Config Updated'), ('rotated', 'Rotated'), ('mint_attempted', 'Mint Attempted'), ('mint_failed', 'Mint Failed'), ('revoke_attempted', 'Revoke Attempted'), ('revoked', 'Revoked'), ('revoke_failed', 'Revoke Failed'), ('orphaned_credential', 'Orphaned Credential'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('manual_rotate', 'Manual Rotate'), ('health_degraded', 'Health Degraded'), ('health_failed', 'Health Failed'), ('health_recovered', 'Health Recovered')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.rotatingsecretcredential')),
                ('organisation_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_events', to='api.organisationmember')),
                ('rotating_secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.rotatingsecret')),
                ('service_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_events', to='api.serviceaccount')),
            ],
        ),
        migrations.AddField(
            model_name='rotatingsecret',
            name='authentication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.providercredentials'),
        ),
        migrations.AddField(
            model_name='rotatingsecret',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.environment'),
        ),
        migrations.AddField(
            model_name='rotatingsecret',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secretfolder'),
        ),
        migrations.AddField(
            model_name='secret',
            name='rotating_secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='api.rotatingsecret'),
        ),
    ]
