# Generated by Django 4.2.30 on 2026-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_rotating_secrets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentsync',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'cancelled'), ('timed_out', 'Timed out'), ('failed', 'Failed')], default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='environmentsyncevent',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'cancelled'), ('timed_out', 'Timed out'), ('failed', 'Failed')], default='queued', max_length=16),
        ),
    ]
