# Generated by Django 4.2.30 on 2026-06-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_rotating_secrets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotatingsecretcredential',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='rotatingsecretcredential',
            name='retire_at',
        ),
        migrations.AddField(
            model_name='rotatingsecretcredential',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providercredentials',
            name='provider',
            field=models.CharField(choices=[('cloudflare', 'Cloudflare'), ('aws', 'AWS'), ('aws_assume_role', 'AWS Assume Role'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('hashicorp_vault', 'Hashicorp Vault'), ('hashicorp_nomad', 'Hashicorp Nomad'), ('railway', 'Railway'), ('vercel', 'Vercel'), ('render', 'Render'), ('azure', 'Azure'), ('openai', 'OpenAI'), ('litellm', 'LiteLLM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rotatingsecretcredential',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expiring', 'Expiring'), ('revoking', 'Revoking'), ('revoked', 'Revoked'), ('mint_failed', 'Mint Failed'), ('revoke_failed', 'Revoke Failed')], default='pending', max_length=20),
        ),
    ]
