# Generated by Django 4.2.30 on 2026-06-02 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_rotation_status_renames'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretevent',
            name='rotating_secret_credential',
            field=models.ForeignKey(
                blank=True,
                null=True,
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='read_events',
                to='api.rotatingsecretcredential',
            ),
        ),
        migrations.AlterField(
            model_name='secretevent',
            name='secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secret'),
        ),
    ]
