# Generated by Django 4.2.30 on 2026-08-02 14:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_add_queued_sync_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='resource_type',
            field=models.CharField(choices=[('app', 'App'), ('env', 'Environment'), ('role', 'Role'), ('sa', 'ServiceAccount'), ('member', 'OrganisationMember'), ('policy', 'NetworkAccessPolicy'), ('pat', 'UserToken'), ('sa_token', 'ServiceAccountToken'), ('svc_token', 'ServiceToken'), ('invite', 'Invite'), ('team', 'Team'), ('rs', 'RotatingSecret'), ('stream', 'LogStream')], max_length=10),
        ),
        migrations.AlterField(
            model_name='providercredentials',
            name='provider',
            field=models.CharField(choices=[('cloudflare', 'Cloudflare'), ('aws', 'AWS'), ('aws_assume_role', 'AWS Assume Role'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('hashicorp_vault', 'Hashicorp Vault'), ('hashicorp_nomad', 'Hashicorp Nomad'), ('railway', 'Railway'), ('vercel', 'Vercel'), ('render', 'Render'), ('azure', 'Azure'), ('openai', 'OpenAI'), ('litellm', 'LiteLLM'), ('datadog', 'Datadog')], max_length=50),
        ),
        migrations.CreateModel(
            name='LogStream',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('provider', models.CharField(help_text='Log stream adapter id (resolved against the log stream adapter registry).', max_length=50)),
                ('sources', models.JSONField(default=list, help_text='Event source ids to ship (resolved against the log stream source registry).')),
                ('options', models.JSONField(default=dict)),
                ('max_attempts', models.PositiveIntegerField(default=5, help_text='Delivery attempts per chunk before it is recorded as failed and skipped.')),
                ('is_active', models.BooleanField(default=True)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded')], default='healthy', max_length=20)),
                ('paused_reason', models.TextField(blank=True, default='')),
                ('cursors', models.JSONField(default=dict)),
                ('ship_job_id', models.TextField(blank=True, null=True)),
                ('last_shipped_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('authentication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_streams', to='api.providercredentials')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_streams', to='api.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='LogStreamDeliveryEvent',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('payload_bytes', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('cursor_from', models.DateTimeField(blank=True, null=True)),
                ('cursor_to', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('job_id', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retried_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='api.logstreamdeliveryevent')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_events', to='api.logstream')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stream', '-created_at'], name='log_stream_delivery_idx')],
            },
        ),
    ]
