# Generated by Django 4.2.30 on 2026-08-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_log_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstreamdeliveryevent',
            name='cursor_from_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='logstreamdeliveryevent',
            name='cursor_to_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
