# Generated by Django 5.2.17 on 2026-08-10 10:54

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # Concurrent index build: LogStreamDeliveryEvent takes continuous writes
    # from the ship path, so a plain CREATE INDEX would block them. Mirrors
    # migration 0112 (SecretEvent).
    atomic = False

    dependencies = [
        ('api', '0133_logstreamdeliveryevent_cursor_from_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logstreamdeliveryevent',
            name='job_id',
        ),
        AddIndexConcurrently(
            model_name='logstreamdeliveryevent',
            index=models.Index(condition=models.Q(('resolved_at__isnull', True), ('status__in', ['failed', 'skipped'])), fields=['stream', 'source'], name='log_stream_unresolved_idx'),
        ),
    ]
