# Generated by Django 4.2.30 on 2026-06-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_auditevent_rotating_secret_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatingsecret',
            name='paused_remaining',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
