# Generated by Django 5.2.17 on 2026-08-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_logstreamdeliveryevent_cursor_from_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logstreamdeliveryevent',
            name='job_id',
        ),
    ]
