# Generated by Django 4.2.30 on 2026-06-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_rotating_secret_paused_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='rotating_output_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='secret',
            name='rotating_secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='api.rotatingsecret'),
        ),
    ]
