# Generated by Django 4.2.30 on 2026-06-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_secret_rotating_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretevent',
            name='rotating_secret_credential',
        ),
    ]
