# Generated by Django 4.2.30 on 2026-06-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_drop_secretevent_rotating_credential_fk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('rotating_secret__isnull', False)), fields=('rotating_secret', 'rotating_output_id'), name='unique_rotating_secret_output'),
        ),
    ]
