# Generated by Django 5.2.17 on 2026-08-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """CASCADE -> SET_NULL on member-attribution FKs so that hard-deleting a
    user (account deletion) cannot cascade away org-owned resources: network
    access policies and live service/service-account tokens.

    Django enforces on_delete in Python, not in DDL -- `sqlmigrate` confirms
    this migration emits no SQL on Postgres.
    """

    dependencies = [
        ('api', '0136_logstream_unresolved_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkaccesspolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_policies_created', to='api.organisationmember'),
        ),
        migrations.AlterField(
            model_name='networkaccesspolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_policies_updated', to='api.organisationmember'),
        ),
        migrations.AlterField(
            model_name='serviceaccounttoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organisationmember'),
        ),
        migrations.AlterField(
            model_name='servicetoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organisationmember'),
        ),
    ]
