# Generated by Django 4.2.30 on 2026-09-07 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_credential_revisions(apps, schema_editor):
    """Give every existing credential its own revision.

    AddField evaluates a callable default once, so adding the column with
    `default=uuid4` would stamp one shared value on every row.
    """
    ProviderCredentials = apps.get_model("api", "ProviderCredentials")
    for pk in ProviderCredentials.objects.values_list("pk", flat=True).iterator():
        ProviderCredentials.objects.filter(pk=pk).update(revision=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0140_supabase_sync_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("harness_type", models.CharField(choices=[("claude_code", "Claude Code"), ("codex", "Codex"), ("cursor", "Cursor"), ("devin", "Devin"), ("opencode", "OpenCode"), ("other", "Other")], default="other", max_length=32)),
                ("status", models.CharField(choices=[("active", "Active"), ("disabled", "Disabled")], default="active", max_length=16)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agents_created", to="api.organisationmember")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agents", to="api.organisation")),
            ],
        ),
        migrations.CreateModel(
            name="AgentConnection",
            fields=[
                ("id", models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("service_type", models.CharField(max_length=64)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("state", models.CharField(choices=[("pending_credentials", "Pending credentials"), ("active", "Active"), ("disabled", "Disabled")], default="pending_credentials", max_length=32)),
                ("host_rules_version", models.TextField(default=uuid.uuid4, editable=False)),
                ("host_rules_approved_version", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentRequest",
            fields=[
                ("id", models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("setup", "Setup"), ("credential_update", "Credential update")], max_length=32)),
                ("markdown", models.TextField()),
                ("service_type", models.CharField(blank=True, max_length=64, null=True)),
                ("credential_provider", models.CharField(blank=True, max_length=50, null=True)),
                ("credential_name", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(choices=[("cancelled", "Cancelled"), ("pending", "Pending"), ("approved", "Approved"), ("denied", "Denied"), ("expired", "Expired")], default="pending", max_length=16)),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("progress", models.JSONField(blank=True, default=dict)),
                ("resolution", models.JSONField(blank=True, default=dict)),
                ("revision", models.TextField(default=uuid.uuid4, editable=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("dedup_key", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("connection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requests", to="api.agentconnection")),
            ],
        ),
        migrations.CreateModel(
            name="AgentWorkflow",
            fields=[
                ("id", models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workflows", to="api.agent")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_workflows_created", to="api.organisationmember")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_workflows", to="api.organisation")),
            ],
        ),
        migrations.CreateModel(
            name="AgentMembership",
            fields=[
                ("id", models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="api.agent")),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_memberships_assigned", to="api.organisationmember")),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_memberships", to="api.organisationmember")),
            ],
        ),
        migrations.CreateModel(
            name="AgentWorkflowMembership",
            fields=[
                ("id", models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("agent_membership", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workflow_memberships", to="api.agentmembership")),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_workflow_memberships_assigned", to="api.organisationmember")),
                ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="api.agentworkflow")),
            ],
        ),
        migrations.AddField(
            model_name="providercredentials",
            name="revision",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(backfill_credential_revisions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="providercredentials",
            name="revision",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="providercredentials",
            name="provider",
            field=models.CharField(
                choices=[
                    ("cloudflare", "Cloudflare"),
                    ("aws", "AWS"),
                    ("aws_assume_role", "AWS Assume Role"),
                    ("postgres", "PostgreSQL"),
                    ("github", "GitHub"),
                    ("gitlab", "GitLab"),
                    ("hashicorp_vault", "HashiCorp Vault"),
                    ("hashicorp_nomad", "HashiCorp Nomad"),
                    ("railway", "Railway"),
                    ("vercel", "Vercel"),
                    ("render", "Render"),
                    ("supabase", "Supabase"),
                    ("azure", "Azure"),
                    ("openai", "OpenAI"),
                    ("litellm", "LiteLLM"),
                    ("datadog", "Datadog"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="resource_type",
            field=models.CharField(choices=[("app", "App"), ("env", "Environment"), ("role", "Role"), ("sa", "ServiceAccount"), ("member", "OrganisationMember"), ("policy", "NetworkAccessPolicy"), ("pat", "UserToken"), ("sa_token", "ServiceAccountToken"), ("svc_token", "ServiceToken"), ("invite", "Invite"), ("team", "Team"), ("rs", "RotatingSecret"), ("stream", "LogStream"), ("agent", "Agent"), ("agent_conn", "AgentConnection"), ("agent_request", "AgentRequest")], max_length=16),
        ),
        migrations.CreateModel(
            name="AgentWorkflowGrant",
            fields=[
                ("id", models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workflow_grants", to="api.agentconnection")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_workflow_grants_created", to="api.organisationmember")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_workflow_grants", to="api.organisation")),
                ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="grants", to="api.agentworkflow")),
            ],
        ),
        migrations.CreateModel(
            name="AgentToken",
            fields=[
                ("id", models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_tokens_created", to="api.organisationmember")),
                ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tokens", to="api.agentworkflow")),
            ],
        ),
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                ("session_uid", models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hashed_session_credential", models.CharField(max_length=128)),
                ("open_idempotency_key", models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("max_expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("config_generation", models.PositiveBigIntegerField(default=1)),
                ("runtime_snapshot", models.JSONField(blank=True, default=dict)),
                ("client_info", models.JSONField(blank=True, default=dict)),
                ("harness_label", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now_add=True)),
                ("agent_token", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sessions", to="api.agenttoken")),
                ("opened_by_member", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_sessions_opened", to="api.organisationmember")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_sessions", to="api.organisation")),
                ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="api.agentworkflow")),
            ],
        ),
        migrations.AddField(
            model_name="agentrequest",
            name="credential",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_requests", to="api.providercredentials"),
        ),
        migrations.AddField(
            model_name="agentrequest",
            name="grant",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requests", to="api.agentworkflowgrant"),
        ),
        migrations.AddField(
            model_name="agentrequest",
            name="organisation",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_requests", to="api.organisation"),
        ),
        migrations.AddField(
            model_name="agentrequest",
            name="related_request",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="followups", to="api.agentrequest"),
        ),
        migrations.AddField(
            model_name="agentrequest",
            name="resolved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_requests_resolved", to="api.organisationmember"),
        ),
        migrations.AddField(
            model_name="agentrequest",
            name="workflow",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requests", to="api.agentworkflow"),
        ),
        migrations.CreateModel(
            name="AgentEvent",
            fields=[
                ("ingest_seq", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_id", models.TextField()),
                ("proxy_created_at", models.DateTimeField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=64)),
                ("protocol", models.CharField(max_length=32)),
                ("method", models.CharField(blank=True, default="", max_length=32)),
                ("host", models.CharField(max_length=512)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("path", models.TextField(blank=True, default="")),
                ("provider", models.CharField(max_length=64)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("proxy_decision", models.CharField(choices=[("allow", "Allow"), ("block", "Block"), ("auth_deny", "Authentication denied"), ("error", "Error")], max_length=32)),
                ("outcome", models.CharField(blank=True, default="", max_length=32)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("credential_action", models.CharField(blank=True, default="", max_length=64)),
                ("bytes_in", models.PositiveBigIntegerField(default=0)),
                ("bytes_out", models.PositiveBigIntegerField(default=0)),
                ("reason", models.CharField(blank=True, default="", max_length=512)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("agent", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="api.agent")),
                ("connection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="api.agentconnection")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_events", to="api.organisation")),
                ("session", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="api.agentsession")),
                ("workflow", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="api.agentworkflow")),
            ],
            options={"ordering": ["-ingest_seq"]},
        ),
        migrations.CreateModel(
            name="AgentDecoy",
            fields=[
                ("id", models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=64)),
                ("field_name", models.CharField(max_length=128)),
                ("decoy_value", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decoys", to="api.agent")),
                ("authentication", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decoys", to="api.providercredentials")),
                ("grant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="decoys", to="api.agentworkflowgrant")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_decoys", to="api.organisation")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="decoys", to="api.agentsession")),
            ],
        ),
        migrations.AddField(
            model_name="agentconnection",
            name="authentication",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_connections", to="api.providercredentials"),
        ),
        migrations.AddField(
            model_name="agentconnection",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_connections_created", to="api.organisationmember"),
        ),
        migrations.AddField(
            model_name="agentconnection",
            name="host_rules_approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_host_rules_approved", to="api.organisationmember"),
        ),
        migrations.AddField(
            model_name="agentconnection",
            name="host_rules_authored_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_host_rules_authored", to="api.organisationmember"),
        ),
        migrations.AddField(
            model_name="agentconnection",
            name="organisation",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_connections", to="api.organisation"),
        ),
        migrations.AddField(
            model_name="agentconnection",
            name="updated_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_connections_updated", to="api.organisationmember"),
        ),
        migrations.AddConstraint(
            model_name="agentworkflowgrant",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("workflow", "connection"), name="unique_active_workflow_connection_grant"),
        ),
        migrations.AddIndex(
            model_name="agentworkflow",
            index=models.Index(fields=["organisation", "agent", "deleted_at"], name="workflow_org_agent_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentworkflow",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("agent", "name"), name="unique_active_agent_workflow_name"),
        ),
        migrations.AddConstraint(
            model_name="agentmembership",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("agent", "member"), name="unique_active_agent_member"),
        ),
        migrations.AddIndex(
            model_name="agentmembership",
            index=models.Index(fields=["member", "deleted_at"], name="agent_member_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentworkflowmembership",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("workflow", "agent_membership"), name="unique_active_workflow_member"),
        ),
        migrations.AddIndex(
            model_name="agentworkflowmembership",
            index=models.Index(fields=["agent_membership", "deleted_at"], name="workflow_member_active_idx"),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(fields=["workflow", "-created_at"], name="agent_session_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(fields=["organisation", "revoked_at", "expires_at"], name="agent_session_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentsession",
            constraint=models.CheckConstraint(check=models.Q(models.Q(("agent_token__isnull", False), ("opened_by_member__isnull", True)), models.Q(("agent_token__isnull", True), ("opened_by_member__isnull", False)), _connector="OR"), name="agent_session_exactly_one_authenticator"),
        ),
        migrations.AddIndex(
            model_name="agentrequest",
            index=models.Index(fields=["organisation", "status", "-created_at"], name="agent_request_queue_idx"),
        ),
        migrations.AddIndex(
            model_name="agentrequest",
            index=models.Index(fields=["workflow", "status", "-created_at"], name="agent_request_workflow_idx"),
        ),
        migrations.AddIndex(
            model_name="agentevent",
            index=models.Index(fields=["agent", "ingest_seq"], name="agent_event_agent_seq_idx"),
        ),
        migrations.AddIndex(
            model_name="agentevent",
            index=models.Index(fields=["workflow", "ingest_seq"], name="agent_event_workflow_seq_idx"),
        ),
        migrations.AddIndex(
            model_name="agentevent",
            index=models.Index(fields=["session", "ingest_seq"], name="agent_event_session_seq_idx"),
        ),
        migrations.AddIndex(
            model_name="agentevent",
            index=models.Index(fields=["organisation", "ingest_seq"], name="agent_event_org_seq_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentevent",
            constraint=models.UniqueConstraint(fields=("session", "event_id"), name="unique_agent_event_id_per_session"),
        ),
        migrations.AddConstraint(
            model_name="agentdecoy",
            constraint=models.UniqueConstraint(fields=("session", "grant", "field_name"), name="unique_agent_decoy_field_per_grant"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["organisation", "deleted_at"], name="agent_org_active_idx"),
        ),
    ]
