version: "3"

services:
  nginx:
    container_name: phase-nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - phase-net

  frontend:
    container_name: phase-frontend
    restart: unless-stopped
    depends_on:
      - backend
    image: phasehq/frontend:test
    env_file: .env
    networks:
      - phase-net

  backend:
    container_name: phase-backend
    restart: unless-stopped
    depends_on:
      - postgres
    image: phasehq/backend:test
    env_file: .env
    environment:
      - NODE_ENV=production
    networks:
      - phase-net

  postgres:
    container_name: phase-postgres
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - phase-postgres-data:/var/lib/postgresql/data
    networks:
      - phase-net

volumes:
  phase-postgres-data:
    driver: local

networks:
  phase-net:
