query GetAppSecretsLogs($appId: ID!, $start: BigInt, $end: BigInt) {
  logs(appId: $appId, start: $start, end: $end) {
    secrets {
      id
      key
      value
      tags {
        id
        name
        color
      }
      version
      comment
      timestamp
      ipAddress
      userAgent
      user {
        email
        username 
        fullName
        avatarUrl
      }
      eventType
      environment {
        id
        envType
        name
        
      }
    }
  }
  secretsLogsCount(appId: $appId)
  environmentKeys(appId: $appId) {
    id
    identityKey
    wrappedSeed
    wrappedSalt
    environment {
      id
    }
  }
}
