query GetAppEnvironments($appId: ID!, $memberId: ID) {
  appEnvironments(appId: $appId, environmentId: null, memberId: $memberId) {
    id
    name
    envType
    identityKey
    wrappedSeed
    wrappedSalt
    createdAt
    app {
      name
      id
    }
    secretCount
    folderCount
    index
    members {
      email
      fullName
      avatarUrl
    }
  }
  sseEnabled(appId: $appId)
  serverPublicKey
}
