query GetAppSecrets($appId: ID!, $memberId: ID, $memberType: MemberType) {
  appEnvironments(
    appId: $appId
    environmentId: null
    memberId: $memberId
    memberType: $memberType
  ) {
    id
    name
    envType
    identityKey
    wrappedSeed
    wrappedSalt
    createdAt
    app {
      name
      id
    }
    secretCount
    folderCount
    index
    members {
      email
      fullName
      avatarUrl
    }
    folders {
      id
      name
      path
    }
    secrets {
      id
      key
      value
      comment
      path
    }
  }
  sseEnabled(appId: $appId)
  serverPublicKey
}
