query GetAppSecretsLogs(
  $appId: ID!
  $start: BigInt
  $end: BigInt
  $eventTypes: [String]
  $memberId: ID
  $memberType: MemberType
  $environmentId: ID
) {
  secretLogs(
    appId: $appId
    start: $start
    end: $end
    eventTypes: $eventTypes
    memberId: $memberId
    memberType: $memberType
    environmentId: $environmentId
  ) {
    logs {
      id
      path
      key
      value
      tags {
        id
        name
        color
      }
      version
      comment
      timestamp
      ipAddress
      userAgent
      user {
        email
        username
        fullName
        avatarUrl
      }
      serviceToken {
        id
        name
      }
      serviceAccount {
        id
        name
        deletedAt
      }
      serviceAccountToken {
        id
        name
        deletedAt
      }
      eventType
      environment {
        id
        envType
        name
      }
      secret {
        id
        path
      }
    }
    count
  }

  environmentKeys(appId: $appId) {
    id
    identityKey
    wrappedSeed
    wrappedSalt
    environment {
      id
    }
  }
}
