query GetAppSecrets($appId: ID!, $memberId: ID, $memberType: MemberType, $path: String) {
  appEnvironments(
    appId: $appId
    environmentId: null
    memberId: $memberId
    memberType: $memberType
  ) {
    id
    name
    envType
    identityKey
    wrappedSeed
    wrappedSalt
    createdAt
    app {
      name
      id
    }
    secretCount
    folderCount
    index
    members {
      email
      fullName
      avatarUrl
    }
    folders {
      id
      name
      path
    }
    secrets(path: $path) {
      id
      key
      value
      comment
      path
    }
    dynamicSecrets(path: $path) {
      id
      name
      path
      description
      provider
      keyMap {
        id
        keyName
      }
    }
  }
  sseEnabled(appId: $appId)
  serverPublicKey
}
