query GetOrgSecretKeys($organisationId: ID!) {
  apps(organisationId: $organisationId) {
    id
    name
    environments {
      id
      name
      wrappedSeed
      wrappedSalt
      secrets {
        id
        key
        path
      }
    }
  }
}
