query GetSecretHistory($appId: ID!, $envId: ID!, $id: ID!) {
  secrets(envId: $envId, id: $id) {
    id
    history {
      id
      key
      value
      path
      tags {
        id
        name
        color
      }
      version
      comment
      timestamp
      ipAddress
      userAgent
      user {
        email
        username
        fullName
        avatarUrl
      }
      serviceToken {
        id
        name
      }
      serviceAccount {
        id
        name
        deletedAt
      }
      eventType
    }
  }
  environmentKeys(appId: $appId, environmentId: $envId) {
    id
    identityKey
    wrappedSeed
    wrappedSalt
  }
}
