query GetServiceTokens($appId: ID!) {
  serviceTokens(appId: $appId) {
    id
    name
    createdAt
    createdBy {
      fullName
      avatarUrl
      self
    }
    expiresAt
    keys {
      id
      
    }
  }
}
