query GetEnvSecretsKV($envId: ID!) {
  folders(envId: $envId, path: "/") {
    id
    name
  }
  secrets(envId: $envId, path: "/") {
    id
    key
    value
    comment
    path
  }
  environmentKeys(environmentId: $envId) {
    id
    identityKey
    wrappedSeed
    wrappedSalt
  }
}
