query GetSecrets($appId: ID!, $envId: ID!, $path: String) {
  secrets(envId: $envId, path: $path) {
    id
    key
    value
    path
    tags {
      id
      name
      color
    }
    comment
    createdAt
    updatedAt
    history {
      id
      key
      value
      tags {
        id
        name
        color
      }
      version
      comment
      timestamp
      ipAddress
      userAgent
      user {
        email
        username
        fullName
        avatarUrl
      }
      eventType
    }
    override {
      value
      isActive
    }
    environment {
      id
      app {
        id
      }
    }
  }
  folders(envId: $envId, path: $path) {
    id
    name
    path
    createdAt
    folderCount
    secretCount
  }
  appEnvironments(appId: $appId, environmentId: $envId) {
    id
    name
    envType
    identityKey
    app {
      name
    }
  }
  environmentKeys(appId: $appId, environmentId: $envId) {
    id
    identityKey
    wrappedSeed
    wrappedSalt
  }
  envSyncs(envId: $envId) {
    id
    environment {
      id
      name
      envType
    }
    serviceInfo {
      id
      name
    }
    options
    isActive
    status
    lastSync
    createdAt
  }
}
