query GetSecrets($appId: ID!, $envId: ID!) {
  secrets(envId: $envId) {
    id
    key
    value
    tags {
      id
      name
      color
    }
    comment
    createdAt
    history {
      id
      key
      value
      tags {
        id
        name
        color
      }
      version
      comment
      timestamp
      user {
        email
        username 
      }
      eventType
    }
  }
  appEnvironments(appId: $appId, environmentId: $envId) {
    id
    name
    envType
    identityKey
  }
  environmentKeys(environmentId: $envId) {
    id
    identityKey
    wrappedSeed
    wrappedSalt
  }
}
