query GetSecrets($appId: ID!, $envId: ID!, $path: String) {
  secrets(envId: $envId, path: $path) {
    id
    key
    value
    path
    tags {
      id
      name
      color
    }
    comment
    createdAt
    updatedAt
    override {
      value
      isActive
    }
    environment {
      id
      app {
        id
      }
    }
  }
  folders(envId: $envId, path: $path) {
    id
    name
    path
    createdAt
    folderCount
    secretCount
  }
  appEnvironments(appId: $appId, environmentId: $envId) {
    id
    name
    envType
    identityKey
    app {
      id
      name
      sseEnabled
    }
  }
  environmentKeys(appId: $appId, environmentId: $envId) {
    id
    identityKey
    wrappedSeed
    wrappedSalt
  }
  envSyncs(envId: $envId) {
    id
    environment {
      id
      name
      envType
    }
    serviceInfo {
      id
      name
    }
    options
    isActive
    status
    lastSync
    createdAt
  }
  dynamicSecrets(envId: $envId, path: $path) {
    id
    name
    description
    provider
    keyMap {
      id
      keyName
    }
    config {
      ... on AWSConfigType {
        usernameTemplate
        groups
        iamPath
        permissionBoundaryArn
        policyArns
        policyDocument
      }
    }
    defaultTtlSeconds
    maxTtlSeconds
    authentication {
      id
      name
    }
    createdAt
  }
}
