# Base layer
FROM node:18-alpine

# Set the working directory 
WORKDIR /app

# Copy over package files 
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install

# Copy all files 
COPY . .

CMD ["npm", "run", "dev"]