# Base layer
FROM node:18-alpine

# Set the working directory 
WORKDIR /app

# Copy over package files 
COPY package.json ./
COPY yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile --no-cache && yarn cache clean

# Copy all files 
COPY . .

CMD ["yarn", "dev"]