# Base layer
FROM node:22-alpine3.20@sha256:2289fb1fba0f4633b08ec47b94a89c7e20b829fc5679f9b7b298eaa2f1ed8b7e

# Set the working directory 
WORKDIR /app

# Copy over package files 
COPY package.json ./
COPY yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile --no-cache && yarn cache clean

# Copy all files 
COPY . .

CMD ["yarn", "dev"]