version: "3"

services:
  nginx:
    container_name: phase-nginx-dev
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - phase-net-dev

  frontend:
    container_name: phase-frontend-staging
    restart: unless-stopped
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      NEXTAUTH_URL: "${HTTP_PROTOCOL}${HOST}"
      OAUTH_REDIRECT_URI: "${HTTP_PROTOCOL}${HOST}"
      BACKEND_API_BASE: "http://backend:8000"
      NEXT_PUBLIC_BACKEND_API_BASE: "${HTTP_PROTOCOL}${HOST}/service"
      NEXT_PUBLIC_NEXTAUTH_PROVIDERS: "${SSO_PROVIDERS}"
      NEXT_PUBLIC_POSTHOG_KEY: "${NEXT_PUBLIC_POSTHOG_KEY}"
    networks:
      - phase-net-dev

  backend:
    container_name: phase-backend-staging
    restart: unless-stopped
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      ALLOWED_HOSTS: "${HOST},backend"
      ALLOWED_ORIGINS: "${HTTP_PROTOCOL}${HOST}"
      SESSION_COOKIE_DOMAIN: "${HOST}"
    networks:
      - phase-net-dev

  postgres:
    container_name: phase-postgres
    image: postgres:15.4-alpine3.17
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - phase-postgres-data-dev:/var/lib/postgresql/data
    networks:
      - phase-net-dev

volumes:
  phase-postgres-data-dev:
    driver: local

networks:
  phase-net-dev:
