query GetAppKmsLogs($appId: ID!, $start: BigInt, $end: BigInt) {
  kmsLogs(appId: $appId, start: $start, end: $end) {
    logs {
      id
      timestamp
      phaseNode
      eventType
      ipAddress
      country
      city
      phSize
    }
    count
  }
}
