query GetApps($organisationId: ID!, $appId: ID) {
  apps(organisationId: $organisationId, appId: $appId) {
    id
    name
    identityKey
    createdAt
    sseEnabled
    environments {
      id
      name
    }
  }
}
