query GetAppDetail($organisationId: ID!, $appId: ID!) {
  apps(organisationId: $organisationId, appId: $appId) {
    id
    name
    description
    identityKey
    createdAt
    appToken
    appSeed
    appVersion
    sseEnabled
  }
}
