query GetApps($organisationId: ID!, $appId: ID) {
  apps(organisationId: $organisationId, appId: $appId) {
    id
    name
    description
    identityKey
    createdAt
    updatedAt
    sseEnabled
    members {
      id
      email
      fullName
      avatarUrl
    }
    serviceAccounts {
      id
      name
    }
    environments {
      id
      name
      envType
      syncs {
        id
        serviceInfo {
          id
          name
          provider {
            id
            name
          }
        }
        status
      }
    }
  }
}
