query GetApps($organisationId: ID!, $appId: ID) {
  apps(organisationId: $organisationId, appId: $appId) {
    id
    name
    identityKey
    createdAt
    sseEnabled
    members {
      id
      identityKey
      email
      fullName
      avatarUrl
      createdAt
      role
    }
    environments {
      id
      name
      envType
      identityKey
      wrappedSeed
      wrappedSalt
      createdAt
      syncs {
        id
        serviceInfo {
          id
          name
          provider {
            id
            name
          }
        }
        status
      }
    }
  }
}
