query GetDashboard($organisationId: ID!) {
  apps(organisationId: $organisationId) {
    id
    name
    sseEnabled
  }
  userTokens(organisationId: $organisationId) {
    id
  }
  organisationInvites(orgId: $organisationId) {
    id
  }
  organisationMembers(organisationId: $organisationId, role: null) {
    id
  }
  savedCredentials(orgId: $organisationId) {
    id
  }
  syncs(orgId: $organisationId) {
    id
  }
}
