query GetOrganisations {
  organisations {
    id
    name
    identityKey
    createdAt
    plan
    planDetail {
      name
      maxUsers
      maxApps
      maxEnvsPerApp
      userCount
      appCount
    }
    role
    memberId
    keyring
    recovery
  }
}
