query GetAgentMesh($organisationId: ID!) {
  agentWorkflows(organisationId: $organisationId) {
    id
    name
    agent {
      id
    }
    grants {
      id
      connection {
        id
        name
        serviceType
        state
        authentication {
          id
          name
          provider {
            id
            name
          }
        }
      }
    }
  }
}
