FROM python:3.12.1-alpine3.19

ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Install dependencies
RUN apk update && apk add --no-cache \
    postgresql-dev \
    build-base \
    gcc \
    musl-dev \
    jpeg-dev \
    zlib-dev \
    libffi-dev \
    cairo-dev \
    pango-dev \
    gdk-pixbuf-dev \
    mariadb-dev \
    python3-dev

COPY requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . /app

EXPOSE 8000

CMD sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
