FROM python:3.11.4-alpine3.18

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app

EXPOSE 8000

CMD sh -c "python manage.py migrate && python manage.py runserver backend:8000"
