query GetAccountDeletionReadiness {
  accountDeletionReadiness {
    canDelete
    requiresReauth
    blockers {
      kind
      organisationId
      organisationName
      detail
    }
    warnings {
      kind
      organisationId
      organisationName
      detail
    }
  }
}
