query GetAccountIdentities {
  accountIdentities {
    identities {
      id
      provider
      providerName
      uid
      email
      name
      avatarUrl
      createdAt
      lastUsedAt
      isLastMethod
      managedByOrg
      blockedReason
      blockedOrgName
      organisationName
    }
    hasUsablePassword
    availableInstanceProviders {
      slug
      providerId
    }
    availableOrgProviders {
      id
      provider
      providerId
      providerName
      organisationName
    }
  }
}
