query GetCheckoutDetails($stripeSessionId: String!, $organisationId: ID!) {
  stripeCheckoutDetails(stripeSessionId: $stripeSessionId, organisationId: $organisationId) {
    paymentStatus
    customerEmail
    billingStartDate
    billingEndDate
    subscriptionId
    planName
  }
}
