export { GoogleLogo } from './Google'
export { GitHubLogo } from './GitHub'
export { GitLabLogo } from './GitLab'
export { JumpCloudLogo } from './JumpCloud'
export { EntraIDLogo } from './EntraID'
export { AuthentikLogo } from './Authentik'
export { AutheliaLogo } from './Authelia'
export { OktaLogo } from './Okta'
