query GetGcpSecretManagerSecrets($credentialId: ID!, $projectId: String!, $location: String!) {
  gcpSecretManagerSecrets(credentialId: $credentialId, projectId: $projectId, location: $location) {
    name
    managedByPhase
  }
}
