query GetOrganisationMembers($organisationId: ID!, $role: [String]) {
  organisationMembers(organisationId: $organisationId, role: $role) {
    id
    role {
      id
      name
      description
      permissions
      color
    }
    identityKey
    email
    fullName
    avatarUrl
    createdAt
    lastLogin
    self
  }
}
