query GetOrganisationPlan($organisationId: ID!) {
  organisationPlan(organisationId: $organisationId) {
    name
    maxUsers
    maxApps
    maxEnvsPerApp
    seatsUsed {
      users
      serviceAccounts
      total
    }
    appCount
  }
}
