query GetOrganisationPlan($organisationId: ID!) {
  organisationPlan(organisationId: $organisationId) {
    name
    maxUsers
    maxApps
    maxEnvsPerApp
    userCount
    serviceAccountCount
    appCount
  }
}
