query GetPendingInvitesForUser {
  pendingInvitesForUser {
    id
    organisation {
      id
      name
    }
    inviteeEmail
    invitedBy {
      fullName
      email
    }
    invitedByServiceAccount {
      id
      name
    }
    expiresAt
    createdAt
  }
}
