query VerifyInvite($inviteId: ID!) {
  validateInvite(inviteId: $inviteId) {
    id
    organisation {
      id
      name
    }
    inviteeEmail
    invitedBy {
      fullName
      email
    }
    apps {
      id
      name
    }
  }
}
