query GetRotationCloneSpec($sourceRotatingSecretId: ID!) {
  rotationCloneSpec(sourceRotatingSecretId: $sourceRotatingSecretId) {
    provider
    authenticationId
    authenticationName
    config
    keyMap {
      id
      keyName
    }
    name
    description
    rotationIntervalSeconds
    revocationDelaySeconds
    sourceEnvironmentId
    sourceEnvironmentName
  }
}
