query ImportRotationTemplate(
  $providerId: String!
  $authenticationId: ID!
  $templateRef: String!
) {
  rotationProviderImportTemplate(
    providerId: $providerId
    authenticationId: $authenticationId
    templateRef: $templateRef
  )
}
