query GetDynamicSecrets($orgId: ID!, $appId: ID, $envId: ID, $path: String) {
  dynamicSecrets(orgId: $orgId, appId: $appId, envId: $envId, path: $path) {
    id
    name
    environment {
      id
      name
      index
      app {
        id
        name
      }
    }
    path
    description
    provider
    config {
      ... on AWSConfigType {
        usernameTemplate
        iamPath
      }
    }
    keyMap {
      id
      keyName
    }
    defaultTtlSeconds
    maxTtlSeconds
    authentication {
      id
      name
    }
    createdAt
  }
}
