query GetDynamicSecretCloneSpec($sourceDynamicSecretId: ID!) {
  dynamicSecretCloneSpec(sourceDynamicSecretId: $sourceDynamicSecretId) {
    provider
    authenticationId
    authenticationName
    config
    keyMap {
      id
      keyName
    }
    name
    description
    defaultTtlSeconds
    maxTtlSeconds
    sourceEnvironmentId
    sourceEnvironmentName
  }
}
