query GetDynamicSecretLeases($secretId: ID!, $orgId: ID!) {
  dynamicSecrets(secretId: $secretId, orgId: $orgId) {
    id
    leases {
      id
      name
      createdAt
      expiresAt
      revokedAt
      status
      organisationMember {
        id
        fullName
        email
        avatarUrl
        self
      }
      serviceAccount {
        id
        name
      }
      events {
        id
        eventType
        createdAt
        metadata
        ipAddress
        userAgent
        organisationMember {
          id
          fullName
          email
          avatarUrl
          self
        }
        serviceAccount {
          id
          name
        }
      }
    }
  }
}
