query GetServiceAccounts($orgId: ID!, $id: ID) {
  serviceAccounts(orgId: $orgId, serviceAccountId: $id) {
    id
    name
    identityKey
    role {
      id
      name
      permissions
    }
    createdAt
    handlers {
      id
      wrappedKeyring
      user {
        self
      }
    }
    tokens {
      id
      name
      createdAt
      expiresAt
      createdBy {
        fullName
        avatarUrl
        self
      }
    }
  }
}
