query GetServiceAccountTokens($orgId: ID!, $id: ID) {
  serviceAccounts(orgId: $orgId, serviceAccountId: $id) {
    id
    tokens {
      id
      name
      createdAt
      expiresAt
      createdBy {
        fullName
        avatarUrl
        self
      }
      createdByServiceAccount {
        id
        name
        identityKey
      }
      lastUsed
    }
  }
}
