query GetServiceAccountDetail($orgId: ID!, $id: ID) {
  serviceAccounts(orgId: $orgId, serviceAccountId: $id) {
    id
    name
    identityKey
    role {
      id
      name
      description
      color
      permissions
    }
    createdAt
    handlers {
      id
      wrappedKeyring
      wrappedRecovery
      user {
        self
      }
    }
    appMemberships {
      id
      name
      environments {
        id
        name
      }
      sseEnabled
    }
    networkPolicies {
      id
      name
      allowedIps
      isGlobal
    }
  }
}
