query GetLogStreamProviders {
  logStreamProviders {
    id
    name
    maxEventAgeHours
    credentialsProvider {
      id
      name
      expectedCredentials
      optionalCredentials
    }
  }
  logStreamSources {
    id
    name
    description
  }
}
