# Generated by Django 4.2 on 2023-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KMSLog',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField(max_length=255)),
                ('app_id', models.TextField()),
                ('phase_node', models.TextField()),
                ('event_type', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('ph_size', models.BigIntegerField()),
                ('asn', models.BigIntegerField()),
                ('isp', models.TextField()),
                ('edge_location', models.TextField()),
                ('country', models.CharField(max_length=2)),
                ('city', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
            ],
        ),
    ]
