# Generated by Django 4.2 on 2023-04-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmslog',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
