# Generated by Django 4.2 on 2023-06-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_kmslog_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KMSLog',
            new_name='KMSDBLog',
        ),
    ]
