# Generated by Django 4.2 on 2023-06-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_rename_kmslog_kmsdblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KMSLog',
        ),
    ]
