# Generated by Django 4.2 on 2023-06-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmsdblog',
            name='asn',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='kmsdblog',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kmsdblog',
            name='country',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='kmsdblog',
            name='edge_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kmsdblog',
            name='isp',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kmsdblog',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='kmsdblog',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
    ]
