# Generated by Django 4.2 on 2023-06-06 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_kmsdblog_asn_alter_kmsdblog_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmsdblog',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
