# Generated by Django 4.2.28 on 2026-02-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_alter_kmsdblog_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KMSDBLog',
        ),
    ]
