query GetAppSyncs($appId: ID!) {
  appSyncs(appId: $appId) {
    id
    environment {
      id
      name
      envType
    }
    serviceInfo {
      id
      name
    }
    options
    isActive
    lastSync
    createdAt
  }
}
