query GetAppSyncStatus($appId: ID!) {
  sseEnabled(appId: $appId)
  syncs(appId: $appId) {
    id
    environment {
      id
      name
      envType
      app {
        id
        name
      }
    }
    path
    serviceInfo {
      id
      name
      provider {
        id
      }
    }
    options
    isActive
    lastSync
    status
    authentication {
      id
      name
      credentials
    }
    createdAt
    history {
      id
      status
      createdAt
      completedAt
      meta
    }
  }
  serverPublicKey 
}
