query GetOrganisationSyncs($orgId: ID!) {
  syncs(orgId: $orgId) {
    id
    environment {
      id
      name
      envType
      app {
        id
        name
      }
    }
    path
    serviceInfo {
      id
      name
      provider {
        id
      }
    }
    options
    isActive
    lastSync
    status
    authentication {
      id
      name
      credentials
    }
    createdAt
    history {
      id
      status
      createdAt
      completedAt
      meta
    }
  }
  savedCredentials(orgId: $orgId) {
    id
    name
    credentials
    createdAt
    provider {
      id
      name
      expectedCredentials
      optionalCredentials
    }
    syncCount
  }
  apps(organisationId: $orgId, appId: null) {
    id
    name
    identityKey
    createdAt
    syncEnabled
  }
}
