query GetOrganisationSyncs($orgId: ID!) {
  syncs(orgId: $orgId) {
    id
    environment {
      id
      name
      envType
      app {
        id
        name
      }
    }
    serviceInfo {
      id
      name
    }
    options
    isActive
    lastSync
    status
    authentication {
      id
      name
      credentials
      provider {
        id
      }
    }
    createdAt
    history {
      id
      status
      createdAt
      completedAt
      meta
    }
  }
}
