query GetSavedCredential($credentialId: ID!) {
  providerCredential(credentialId: $credentialId) {
    id
    name
    revision
    credentials
    createdAt
    updatedAt
    provider {
      id
      name
      expectedCredentials
      optionalCredentials
      nonSensitiveCredentials
    }
    syncCount
    agentConnectionCount
  }
}
