query GetSavedCredentials($orgId: ID!) {
  savedCredentials(orgId: $orgId) {
    id
    name
    credentials
    createdAt
    provider {
      id
      name
      expectedCredentials
      optionalCredentials
    }
    syncCount
  }
}
