query GetAwsSecrets($accessKeyId: String!, $secretAccessKey: String!, $region: String!) {
  awsSecrets(accessKeyId: $accessKeyId, secretAccessKey: $secretAccessKey, region: $region) {
    name
    arn
  }
}
