query ValidateAWSAssumeRoleCredentials($roleArn: String!, $region: String, $externalId: String) {
  validateAwsAssumeRoleCredentials(roleArn: $roleArn, region: $region, externalId: $externalId) {
    valid
    message
    error
    assumedRoleArn
  }
} 