query GetAppServiceAccounts($appId: ID!) {
  appServiceAccounts(appId: $appId) {
    id
    identityKey
    name
    createdAt
    role {
      id
      name
      description
      permissions
      color
    }
    tokens {
      id
      name
    }
  }
}
