query GetGitLabResources($credentialId: ID!) {
  gitlabProjects(credentialId: $credentialId) {
    id
    name
    namespace {
      name
    }
    pathWithNamespace
    webUrl
  }
  gitlabGroups(credentialId: $credentialId) {
    id
    fullName
    fullPath
    webUrl
  }
}
