query GetSCIMTokens($organisationId: ID!) {
  scimTokens(organisationId: $organisationId) {
    id
    name
    tokenPrefix
    createdBy {
      id
      fullName
      email
      avatarUrl
    }
    createdAt
    expiresAt
    lastUsedAt
    isActive
  }
}
